name: Release with commit

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v3.0.0
        with:
          regexp: "((\\d+([.]\\d+)*)\\d*)((\\s|\\S)*)"
          regexp_options: "us"
          release_name: "OCR-Support $1"
          tag_name: "v$1"
          body: "$4"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
